name: Push to develop

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  TF_LOG: INFO

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.7
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Setup Terraform Backend
      id: backend
      run: |
        cat > backend.tf << EOF
        terraform {
          backend "remote" {
            organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"

            workspaces {
              name = "${{ secrets.TF_CLOUD_WORKSPACE }}"
            }
          }
        }
        EOF

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Apply
      id: plan
      run: terraform apply
