name: Workflow for release branch pull requests

on:
  push:
    branches: [ "release/*" ]
  workflow_dispatch:

jobs:
  build:

    name: Hello world action
    runs-on: ubuntu-latest

    steps:
      - name: Identify release/
        run: echo "release/ pull request"
